### ISSUE TITLE
Remote storage is not publicly accessible (dvc pull fails)

### ISSUE THREAD

**Issue by nsorros** [MantisAI/Rasa-MLOPs#5]
`ERROR: unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden`

`dvc pull` needs mantis creds so a reader will not be able to follow. we need to make the bucket public and read only.

**Comment by ivyleavedtoadflax** [comment]
I've done this at the bucket level, not at the individual object level, because they are added by dvc. It _should_ be working...

**Comment by ivyleavedtoadflax** [comment]
btw this issue is probably badly named because:
1. You only need to set `AWS_PROFILE` if you have more than one set of aws credentials
2. You can also set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in the folder to the same effect, and users can decide how best to do this.
